DSG-560 add mySelf endpoint and tests
Nuvalence/dsgov-user-management pull request #64
Opened 2023-05-02 17:50 UTC by afcalderonm

## Description
create new endpoints to get and update the current login user

## Motivation and Context
it will be more easier to update the current login user from the frontend

## Areas for Focus

## How Has This Been Tested?
it was test locally using skaffold and calling the endpoints from postman

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-05-02 22:40 UTC, jgnuvalence approved these changes

2023-05-02 22:40 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/user/management/api/service/controller/UsersApiDelegateImpl.java
> +    public void checkPermission(
I think this cam be private right?

2023-05-02 22:40 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/user/management/api/service/controller/UsersApiDelegateImpl.java
>          if (!authorizationHandler.isAllowed("update", UserEntity.class)) {
Just out of curiosity, is there a reason why you don't use the checkPermission method here?

2023-05-02 22:40 UTC, jgnuvalence commented on service/src/main/java/io/nuvalence/user/management/api/service/controller/UsersApiDelegateImpl.java
> +    @Transactional
I'm probably not understanding something, why are you using @Transactional here?

2023-05-02 22:44 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/user/management/api/service/controller/UsersApiDelegateImpl.java
> +    public void checkPermission(
yeah, i miss that, i will fix it

2023-05-02 22:47 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/user/management/api/service/controller/UsersApiDelegateImpl.java
> +    @Transactional
i was a copy paste error i will fix it

2023-05-02 23:01 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/user/management/api/service/controller/UsersApiDelegateImpl.java
> +    public ResponseEntity<UserDTO> getMySelf() {
Does this need to be public ?

2023-05-02 23:04 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/user/management/api/service/service/UserService.java
> +        String userId = "";
Instead of returning "" , can you return Optional ?

2023-05-02 23:06 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/user/management/api/service/controller/UsersApiDelegateImpl.java
> +        userService.updateUserById(user.getId(), body);
if in class , you have method
`ResponseEntity<UserDTO> updateUserById`
why not re-use it ?

2023-05-02 23:13 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/user/management/api/service/controller/UsersApiDelegateImpl.java
> +        String userId = userService.getUserIdByAuthentication();
As this in your current  code could return "" (preferably I think it should return an Optional object) , Should you validate this does not return values ?

2023-05-02 23:15 UTC, deibys-nuvalence commented on swagger.yaml
> +        "401":
I think 403 is more appropriate here than 401 code

2023-05-02 23:16 UTC, deibys-nuvalence commented on swagger.yaml
> +        "401":
Same here 403 may be more suitable than 401 for this scenario

2023-05-02 23:30 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/user/management/api/service/entity/UserEntity.java
> +            fetch = FetchType.EAGER)
unless strictly necessary , I think it is good practice to delay loading of children objects until needed. Any reason why not to use deault LAZY  fetch type ?

2023-05-03 12:42 UTC, JayStGelais requested changes

2023-05-03 12:42 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/user/management/api/service/controller/UsersApiDelegateImpl.java
> +        checkPermission("view", authorizationHandler);
This check will (should) always fail for public portal users as their permission to view user data is conditional. This is why we applied the filter previously in `getUserById`. We need to make the call that includes the specific user being requested.

2023-05-03 12:42 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/user/management/api/service/service/UserService.java
> +        String userId = "";
Also, we should be using `getApplicationUserId()` when we can assert that the `Authentication` is an `UserToken`

2023-05-03 13:28 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/user/management/api/service/entity/UserEntity.java
> +            fetch = FetchType.EAGER)
ok it makes sense to have custom methods in the repository service to load the children collections if needed and not have EAGER fetch type in the entity

2023-05-03 13:31 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/user/management/api/service/controller/UsersApiDelegateImpl.java
>      private final String userNotFound = "User not found!";
Should this declared as **final static** ?

2023-05-04 17:09 UTC, JayStGelais requested changes

2023-05-04 17:09 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/user/management/api/service/controller/UsersApiDelegateImpl.java
> +    private static final String userNotFound = "User not found!";
Thsi variable should match the naming convention for constants, as well as it coudl stand to be a little more descriptive.

Maybe something like `USER_NOT_FOUND_EXCEPTION_MESSGE`

2023-05-04 17:28 UTC, JayStGelais approved these changes

2023-05-04 17:29 UTC, merged