DSG-886/Add-new-fields-to-user-profile
Nuvalence/dsgov-user-management pull request #89
Opened 2023-06-08 15:26 UTC by afcalderonm

## Description
drop DisplayName and add firstName, middleName, lastName and phoneNumber to the userEntity

## Motivation and Context
To better support user profile management

## Areas for Focus

## How Has This Been Tested?
tested modifying the automated test that already exist and also tested manually from postman

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [ ] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [ ] I have confirmed all acceptance criteria defined by the story have been met

2023-06-08 16:14 UTC, asultan001 commented on acceptance-tests/src/functionalTest/resources/io/nuvalence/platform/features/RoleManagement.feature
>      And a GET request is made for application roles for the user with externalId "test-user"
We probably want to add similar tests for other other properties or enhance this test to include the other properties?

2023-06-08 16:18 UTC, deibys-nuvalence commented on swagger.yaml
> -        displayName:
There are serveral other services (exampple work manager ) which query user-management to get displayName , since it is gone , in order to keep backwards compatibility, you should:
1. Change user-management client in other services
2. At least in the api response , keep the field and make it the union of firstname + middleName + lastname
3. FE will query user management to get the names to display per user

2023-06-08 16:19 UTC, asultan001 commented on swagger.yaml
> +          description: User's phoneNumber.
separate the word phone number in the description

2023-06-08 16:21 UTC, asultan001 commented
@afcalderonm can we add a few tests that validate that you can use null values here as well? I believe these properties should be optional.

2023-06-08 16:33 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/user/management/api/service/service/UserService.java
> +        userEntity.setPhoneNumber(updateRequest.getPhoneNumber());
Maybe it is not in requirements, but would be nice to validate a standard formatting for phone numbers
A library that can be helpful:
https://mvnrepository.com/artifact/com.googlecode.libphonenumber/libphonenumber

2023-06-08 16:34 UTC, deibys-nuvalence commented on service/src/test/java/io/nuvalence/user/management/api/service/auth/UsersApiDelegateImpl.java
> -        user.setDisplayName("Rusty Popins");
Renaming this class to follow standard would be nice
I mean appending "Test" to class name

2023-06-08 16:36 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/user/management/api/service/service/UserService.java
> +        updateNames(userEntity, updateRequest);
Not sure if it is a requirement, but would be good to validate at least one of the names fields is set

2023-06-08 16:47 UTC, asultan001 commented on swagger.yaml
> -        displayName:
It's not a bad idea to maintain the display name as a combination of the other names for backwards compatibility

2023-06-08 18:56 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/user/management/api/service/cerbos/CerbosClient.java
> +                                .instances(
This class, `CerbosClient` should have been removed when we removed the Controller methods that called it. This has been replaced by the generic access control services brought in with the `dsgov-auth` library.

2023-06-08 18:56 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/user/management/api/service/service/UserService.java
> +        updateNames(userEntity, updateRequest);
Freshly minted users may not have any of the 3 name fields set as we can't depend on Identity Providers to have a value.

For example, Google Identity Platform email/password user pools only have an email address to describe the user.

2023-06-08 18:56 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/user/management/api/service/service/UserService.java
> +        userEntity.setPhoneNumber(updateRequest.getPhoneNumber());
Lets pause on validation of phone numbers for now. 

In general we handle formatting on the front end, and just store a string of digits internally. Any validation on what lenght that string needs to be would need to take into account the country involved. I thik it would be better for this solution to be flexible with what it can accept and address validations to meet specific client requirements as they come up in engagements.

2023-06-08 18:56 UTC, JayStGelais commented on service/src/test/java/io/nuvalence/user/management/api/service/service/CerbosClientTest.java
> +        userEntity.setFirstName(allowRole);
We should also delete this test, in addition to the class it is testing.

2023-06-08 18:56 UTC, JayStGelais commented on swagger.yaml
> -        displayName:
For now including displayName on the API model and have it concatenate `firstName + " " + lastName`.

There are some cultures where this logic is incorrect, but it is a worst a temporary fix for backwards compatibility.

2023-06-09 18:39 UTC, afcalderonm commented on acceptance-tests/src/functionalTest/resources/io/nuvalence/platform/features/RoleManagement.feature
>      And a GET request is made for application roles for the user with externalId "test-user"
i just modify the test to include the other properties

2023-06-09 18:39 UTC, afcalderonm commented on swagger.yaml
> +          description: User's phoneNumber.
fixed

2023-06-09 18:40 UTC, afcalderonm commented on service/src/test/java/io/nuvalence/user/management/api/service/auth/UsersApiDelegateImpl.java
> -        user.setDisplayName("Rusty Popins");
fixed

2023-06-09 18:40 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/user/management/api/service/cerbos/CerbosClient.java
> +                                .instances(
the class was removed

2023-06-09 18:40 UTC, afcalderonm commented on service/src/test/java/io/nuvalence/user/management/api/service/service/CerbosClientTest.java
> +        userEntity.setFirstName(allowRole);
the test class was deleted

2023-06-09 18:41 UTC, afcalderonm commented on swagger.yaml
> -        displayName:
the displayName was included concatenated with firstName + " " + lastName

2023-06-09 18:52 UTC, afcalderonm commented
> @afcalderonm can we add a few tests that validate that you can use null values here as well? I believe these properties should be optional.

i just add a few test to validate its possible to update the user profile with the new values null and also to get a user that has those values null

2023-06-09 19:12 UTC, JayStGelais requested changes

2023-06-09 19:40 UTC, asultan001 commented on service/src/main/java/io/nuvalence/user/management/api/service/controller/UsersApiDelegateImpl.java
> +        userDto.setDisplayName(
I think we should trim this operation as well so that we can avoid the following:

Firstname but null lastime -> "Abe " 
Lastname but null firstname -> " Sultan"
null firstname and lastname -> " " 

Instead if you trim them it should be "Abe", "Sultan", ""

2023-06-09 20:21 UTC, JayStGelais requested changes

2023-06-09 20:21 UTC, JayStGelais commented on service/src/main/java/io/nuvalence/user/management/api/service/controller/UsersApiDelegateImpl.java
> +        userDto.setDisplayName(UserEntityMapper.INSTANCE.createDisplayname(user));
What I meant by the previous comment was that this should happen automatically when mapping a UserEntity to a UserDTO. This could be done by adding the followin annotation to `convertUserEntityToUserModel`

`@Mapping(target = "displatName", expression = "java(createDisplayname(userEntity))")`

2023-06-13 14:17 UTC, afcalderonm commented on service/src/main/java/io/nuvalence/user/management/api/service/controller/UsersApiDelegateImpl.java
> +        userDto.setDisplayName(UserEntityMapper.INSTANCE.createDisplayname(user));
oh, i did not know you can do that, now is applied

2023-06-13 14:26 UTC, JayStGelais approved these changes

2023-06-13 14:39 UTC, merged