Dsg 1105 user type search
Nuvalence/dsgov-user-management pull request #91
Opened 2023-06-28 21:13 UTC by deibys-nuvalence

## Description
JIRA https://dol-ewf.atlassian.net/browse/DSG-1105

## Motivation and Context
Add userType in user search

## Areas for Focus

## How Has This Been Tested?

## Screenshots (if appropriate):

## Types of changes

Patch
- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] Documentation change (documentation only, will not require redeployment)
- [ ] Refactor or cleanup (functionality unchanged)
Minor
- [X] New feature (non-breaking change which adds functionality)
Major
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [X] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [ ] I have performed a self-review of my own code
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] Any dependent changes have been merged and published in downstream modules

- [X] I have confirmed all acceptance criteria defined by the story have been met

2023-06-28 21:26 UTC, deibys-nuvalence commented on service/src/main/java/io/nuvalence/user/management/api/service/service/UserSearchCriteria.java
> +            predicates.add(
This is hack as comparing the enum directly was not working
Bellow did not work, so I changed the query to compare Strings not enums
```

criteriaBuilder.equal(
                            criteriaBuilder.lower(root.get("userType")),
                            enumUserType));
```

2023-06-28 21:27 UTC, deibys-nuvalence commented on service/src/main/resources/db/liquibase-changelog.xml
> +        <update tableName="user_table">
This is to change current values in database so they are aligned with persisting string not integers

2023-06-29 02:20 UTC, asultan001 commented on swagger.yaml
> +            enum:
@deibys-nuvalence I think we normally use pattern matching instead of enum types because the error messages we get back from the Service are more user friendly. @jgnuvalence or @jcsuarezm may be able to provide guidance on this.

2023-06-29 02:20 UTC, asultan001 requested changes
Left a small comment but otherwise this looks good to me.

2023-06-29 13:48 UTC, deibys-nuvalence commented on swagger.yaml
> +            enum:
done

2023-06-29 13:51 UTC, asultan001 approved these changes
LGTM

2023-06-29 13:53 UTC, merged